version: '3'

services:
    nginx:
        image: nginx:latest
        volumes:
            - ../backend:/var/www
            - ./backend/nginx/conf.d:/etc/nginx/conf.d
        ports:
            - "8876:80"
        depends_on:
            - app
        container_name: nginx

    app:
        build:
            context: ../backend
            dockerfile: ../infra/backend/app/Dockerfile

        user: '1000:1000'

        volumes:
            - ../backend:/var/www
        container_name: app

    frontend:
        container_name: front
        build:
            context: ../frontend
            dockerfile: ../infra/frontend/Dockerfile

        user: '1000:1000'

        volumes:
            - ../frontend:/app
        restart: always
        ports:
            - "88:8080"
        depends_on:
            - app

    db:
        image: mysql:8.0
        restart: always
        volumes:
            - ./mysql/tmp/db:/var/lib/mysql
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: root
        ports:
            - 8101:3306
        command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
        container_name: db

